//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuVienSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyMuon
    {
        public string MaMuon { get; set; }
        public string MaThe { get; set; }
        public string TenSV { get; set; }
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public int SoLuong { get; set; }
        public string GhiChuSV { get; set; }
        public string GhiChuNV { get; set; }
        public string NgayMuon { get; set; }
        public string NgayTra { get; set; }
        public string TinhTrang { get; set; }
    }
}
