//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuVienSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string TacGia { get; set; }
        public string NhomSach { get; set; }
        public string GhiChu { get; set; }
        public int SoLuong { get; set; }
        public string NhaXuatBan { get; set; }
        public string NoiXuatBan { get; set; }
        public string NamXuatBan { get; set; }
        public string NgayNhap { get; set; }
        public string TenFile { get; set; }
    }
}
