//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuVienSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDN
    {
        public string MaThe { get; set; }
        public string TenSV { get; set; }
        public string MSSV { get; set; }
        public string Lop { get; set; }
        public string Email { get; set; }
        public string UserTK { get; set; }
        public string MK { get; set; }
        public string ThoiHan { get; set; }
        public Nullable<int> nam { get; set; }
    }
}
